[package]
name = "sha1-cracker"
version = "1.0"
authors = "Nullfuzz"
edition = "2022"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.10.0"
hex = "0.4.3"